version: '3.3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgreDB
    environment:
      - DATABASE_URL=postgresql://stud:stud@postgreDB/archdb

  postgreDB:
    image: postgres:14
    container_name: postgreDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - POSTGRES_DB=archdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: